int Ball_w = 2;
int Ball_h = 2;
int Ball_x = 39;
int Ball_y = 7;
float Ball_xF = (float) Ball_x;
float Ball_yF = (float) Ball_y;
int Ball_xLoc;
int Ball_yLoc;
int Ball_xMod;
int Ball_yMod;
float Ball_xV = 64.0f;
float Ball_yV = 0.0f;
int Ball_splitsX = 0;
int Ball_splitsY = 0;
int Ball_pastX;
int Ball_pastY;
int Ball_pastSplitsX = 0;
int Ball_pastSplitsY = 0;
int PL_x = 0;
int PL_y = 5;
int PL_w = 5;
int PL_h = 6;
int PL_xLoc = 0;
int PL_yLoc;
int PL_yMod;
int PL_splits = 0;
int PR_x = 75;
int PR_y = 5;
int PR_w = 5;
int PR_h = 6;
int PR_xLoc = 15;
int PR_yLoc;
int PR_yMod;
int PR_splits = 0;
int PR_dir = 0;
float PR_yV = 6.0f;
int LCD_w = 80;
int LCD_h = 16;
int LCD_cX = 16;
int LCD_cY = 2;
int LCD_cW = 5;
int LCD_cH = 8;
